### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [luratic/BelboonPerformance#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUri should be used on user provided values that are then used as part of your url. These methods take in a single text argument and return a string that represents the provided string encoded as a URI.
const trackingUrl = 'https://' + advertiserDomain + '/ts/' + advertiserId + '/tsa?typ=i&tst=' + getTimestamp() + '&trc=' + productCategory + '&ctg=' + conversionTarget + '&sid=' + shortDesc + '&cid=' + conversionId + '&orv=' + conversionValue + '&orc=' + currencyCode;

**Comment by luratic-devs** [comment]
@praveena-pappu Many thanks!
